image: python:3.11

stages:
  - unit_test
  - test
  - lint
  - integration_test
  - e2e_test
  - containerize
  - trivy-container-scan

# Security templates from GitLab
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8 semgrep pytest requests

unit_tests:
  stage: unit_test
  script:
    - pytest myapp/test_routes.py

trufflehog-secrets:
  stage: test
  image: alpine:latest
  variables:
    SCAN_PATH: "."
  before_script:
    - apk add --no-cache git curl jq
    - curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
  script:
    - trufflehog filesystem "$SCAN_PATH"
  allow_failure: false

sast-python:
  stage: test
  image: returntocorp/semgrep
  script:
    - semgrep scan --config auto .
  allow_failure: false

lint:
  stage: lint
  script:
    - flake8 myapp

integration_tests:
  stage: integration_test
  script:
    - pytest myapp/test_integration.py

e2e_tests:
  stage: e2e_test
  script:
    - pytest myapp/test_e2e.py

containerize:
  image: docker:latest
  stage: containerize
  services:
    - docker:dind
  script:
    - docker build -t flask-starter-app .

trivy-container-scan:
  image: docker:stable
  stage: trivy-container-scan
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
    - docker build -t flask-starter-app .
    - ./trivy image flask-starter-app -f json -o trivy-report.json --severity HIGH,CRITICAL
  artifacts:
    paths:
      - trivy-report.json
    expire_in: 1 week

