name: Flask App CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Create Virtual Environment and Install Dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt
          pip install flake8 semgrep pytest requests  # Ensure pytest is installed

      - name: Verify pytest installation
        run: |
          source venv/bin/activate  # Activate the virtual environment
          echo "Verifying pytest installation"
          pip show pytest  # Show pytest details
          pytest --version  # Ensure pytest is installed

  unit_tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: |
          source venv/bin/activate  # Activate the virtual environment
          echo "Running unit tests"
          pytest myapp/test_routes.py

  trufflehog_secrets:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Run TruffleHog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
          trufflehog filesystem .

  semgrep_sast:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Run Semgrep SAST
        run: |
          source venv/bin/activate  # Activate the virtual environment
          echo "Running Semgrep SAST"
          semgrep scan --config auto .

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Lint code
        run: |
          source venv/bin/activate  # Activate the virtual environment
          echo "Running flake8"
          flake8 myapp

  integration_tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Run integration tests
        run: |
          source venv/bin/activate  # Activate the virtual environment
          echo "Running integration tests"
          pytest myapp/test_integration.py

  e2e_tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Run E2E tests
        run: |
          source venv/bin/activate  # Activate the virtual environment
          echo "Running E2E tests"
          pytest myapp/test_e2e.py

  containerize:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t flask-starter-app .

  trivy_scan:
    runs-on: ubuntu-latest
    needs: containerize
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Trivy
        run: |
          TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
          tar zxvf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan Image with Trivy
        run: |
          docker build -t flask-starter-app .
          trivy image flask-starter-app -f json -o trivy-report.json --severity HIGH,CRITICAL

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.json
