name: Docker Image Vulnerability Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Trivy
      uses: aquasecurity/trivy-action@master
      with:
        version: '0.61.1'

    - name: Build Docker Image
      run: |
        echo "🛠 Building Docker image..."
        sudo docker build -t flask-starter-app:latest .
        sudo docker images

    - name: Check if Image Exists
      run: |
        echo "🔍 Verifying Docker image exists..."
        if ! sudo docker image inspect flask-starter-app:latest > /dev/null 2>&1; then
          echo "❌ Image flask-starter-app:latest not found!"
          exit 1
        else
          echo "✅ Image found."
        fi

    - name: Ensure Docker Daemon is Running
      run: |
        echo "🔧 Checking Docker daemon status..."
        if ! sudo docker info > /dev/null 2>&1; then
          echo "⚠️ Docker daemon not running. Attempting to start..."
          sudo systemctl start docker
        fi

    - name: Run Trivy Vulnerability Scan
      run: |
        echo "🔎 Running Trivy scan..."
        sudo trivy image --severity HIGH,CRITICAL --no-progress -f json -o trivy-report.json flask-starter-app:latest

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy-report.json
